index:
    path: /
    controller: App\Training\UI\Web\Action\ShowDashboardAction

training.create.page:
    path: /training/create
    controller: App\Training\UI\Web\Action\ShowTrainingCreatePageAction
    methods: GET

training.create:
    path: /training/create
    controller: App\UI\Web\Action\Training\CreateTrainingAction
    methods: POST

api.training.maps:
    path: /api/maps
    controller: App\UI\Api\Action\Training\GetAllMapsAction
    methods: [ GET, OPTIONS ]

training.edit.page:
    path: /training/{id}/edit
    controller: App\UI\Web\Action\Training\ShowTrainingEditPageAction
    methods: GET

training.edit:
    path: /training/{id}/edit
    controller: App\UI\Web\Action\Training\EditTrainingAction
    methods: POST

training.part.end:
    path: /training/part/{id}/end
    controller: App\UI\Web\Action\Training\EndTrainingPartAction
    methods: GET

training.part.reopen:
    path: /training/part/{id}/reopen
    controller: App\UI\Web\Action\Training\ReopenTrainingPartAction
    methods: GET