dashboard:
    path: /
    controller: App\Common\UI\Web\IndexController::dashboard
    methods: GET

training.dashboard:
    path: /training
    controller: App\Training\UI\Web\TrainingController::dashboard
    methods: GET

training.create.page:
    path: /training/create
    controller: App\Training\UI\Web\TrainingController::createPage
    methods: GET

training.create:
    path: /training/create
    controller: App\Training\UI\Web\TrainingController::create
    methods: POST

training.edit.page:
    path: /training/{id}/edit
    controller: App\Training\UI\Web\TrainingController::editPage
    methods: GET

training.update:
    path: /training/{id}/edit
    controller: App\Training\UI\Web\TrainingController::update
    methods: POST

training.part.toggleIsEnded:
    path: /training/part/{id}/toggle
    controller: App\Training\UI\Web\TrainingPartController:toggleIsEnded
    methods: GET

faceit.dashboard:
    path: /faceit/{nickname}
    controller: App\Faceit\UI\Web\DashboardController::dashboard
    methods: GET

api.faceit.players:
    path: /api/v1/faceit/players
    controller: App\Faceit\UI\Api\PlayerController::getAll
    methods: [GET, OPTIONS]

api.faceit.player.information:
    path: /api/v1/faceit/player
    controller: App\Faceit\UI\Api\PlayerController::getPlayerInformation
    methods: [GET, OPTIONS]

api.faceit.player.statistics:
    path: /api/v1/faceit/player/statistics
    controller: App\Faceit\UI\Api\StatisticsController::getByPlayer
    methods: [GET, OPTIONS]

api.faceit.player.matches:
    path: /api/v1/faceit/player/matches
    controller: App\Faceit\UI\Api\MatchController::getByPlayer
    methods: [GET, OPTIONS]