index:
    path: /
    controller: App\Training\UI\Web\TrainingController::dashboard

training.create.page:
    path: /training/create
    controller: App\Training\UI\Web\TrainingController::createPage
    methods: GET

training.create:
    path: /training/create
    controller: App\Training\UI\Web\TrainingController::create
    methods: POST

training.edit.page:
    path: /training/{id}/edit
    controller: App\Training\UI\Web\TrainingController::editPage
    methods: GET

training.update:
    path: /training/{id}/edit
    controller: App\Training\UI\Web\TrainingController::update
    methods: POST

training.part.toggleIsEnded:
    path: /training/part/{id}/toggle
    controller: App\Training\UI\Web\TrainingPartController:toggleIsEnded
    methods: GET
